spring:
  application:
    name: ${SPRING_APPLICATION_NAME:team-nest-api}

  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  # Flyway Configuration
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}

app:
  frontend:
    url: ${APP_FRONTEND_URL}

  role:
    default:
      name: ${APP_DEFAULT_ROLE_NAME:PLATFORM_ADMIN}

  jwt:
    secret:
      key: ${APP_JWT_SECRET_KEY}
    expiration:
      ms: ${APP_JWT_EXPIRATION_MS}
