spring:
  application:
    name: team-nest-api

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:team_nest_db
    driverClassName: org.h2.Driver
    username: sa
    password: 12345

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  frontend:
    url: ${APP_FRONTEND_URL}

  role:
    default:
      name: ${APP_DEFAULT_ROLE_NAME}

  jwt:
    secret:
      key: ${APP_JWT_SECRET_KEY}
    expiration:
      ms: ${APP_JWT_EXPIRATION_MS}
